### ISSUE TITLE
Sources for MT6582

### ISSUE THREAD

**Issue by s0rd3s** [gamblingaddict/android_device_lenovo_a3300#1]
Hello! I really admire your work, if you need sources for proprietary libraries(for building new RIL libs, or bringing up cameras) for MT6582, just say the word. I have access to Mediatek sources for Android 4.4.2, 5.0.2 and 5.1 for this platform.

**Comment by gamblingaddict** [comment]
That would actually be a great help! If you have sources for ccci_mdinit, the sensors hal, and the audio hal, that would be greatly appreciated. Having sources that match the kernel should narrow down where the issues are from.
